apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  namespace: handson
data:
  app.cnf: |
    [mysqld]
    default-authentication-plugin = mysql_native_password
    skip-host-cache
    skip-name-resolve
