apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: handson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      namespace: handson
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "ghost-db.handson.svc.cluster.local"
            - name: database__connection__port
              value: "3306"
            - name: database__connection__user
              value: "ghost-user"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
            - name: database__connection__database
              value: "ghost"
            - name: database__debug
              value: "false"
            - name: server__host
              value: "0.0.0.0"
            - name: server__port
              value: "2368"
            - name: paths__contentPath
              value: "content/"
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: handson
spec:
  ports:
    - port: 2368
      protocol: TCP
      targetPort: 2368
  selector:
    app: ghost
